### ISSUE TITLE
INSPEC: VCSA-70 controls using Vmware.Vsphere.SsoAdmin fail

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#128]
### Describe the bug

All controls which utilize the Vmware.Vsphere.SsoAdmin module fail except for VCSA-70-000290 and VCSA-70-000291 which are expected to be empty for compliance.

Output for each control shows that no data was returned.

### Reproduction steps

1. Execute an inspec scan against controls using the SsoAdmin module.

### Expected behavior

Controls should return data showing compliance or non-compliance.

### Additional context

Windows 2019, Powershell 5.1, Inspec 5.21.29, Vmware.Vsphere.SsoAdmin 1.3.8, VMware.PowerCLI 13.0.0.20829139

Example command:
inspec exec . -t vmware:// --input-file .\inputs-example.yml --show-progress --reporter=cli json:C:\Inspec\Reports\vcsa.json --controls=VCSA-70-000266

I am unable to properly troubleshoot this. Executing the inspec scan gives me no feedback that I can use.
ProcMon shows me that a powershell session is opened and the Vmware.Vsphere.SsoAdmin module is being read, but I am at a loss as to how to proceed.

**Comment by rlakey** [comment]
Can you provide the output you are seeing?  Do the other checks that use SsoAdmin working?

Also did you install the custom vmware-train?

**Comment by pbarrette** [comment]
Ah.. I missed the plugin install.

Now I'm getting this:
```
Invalid gemspec in [C:/Users/XXX/.inspec/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/ffi.gemspec]: No such file or directory - git ls-files -z
C:/inspec/inspec/embedded/lib/ruby/3.1.0/rubygems/resolver/vendor_set.rb:39:in `add_vendor_gem': unable to find C:/Users/XXX/.inspec/gems/3.1.0/gems/ffi-1.15.5-x64-mingw-ucrt/ffi.gemspec for gem ffi (Gem::GemNotFoundException)
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:190:in `block (2 levels) in activate_managed_gems_for_plugin'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:189:in `chdir'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:189:in `block in activate_managed_gems_for_plugin'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:182:in `each'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:182:in `activate_managed_gems_for_plugin'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:313:in `fixup_train_plugin_status'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:40:in `block in initialize'
        from C:/inspec/inspec/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `each'
        from C:/inspec/inspec/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `each'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/plugin/v2/loader.rb:39:in `initialize'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/cli.rb:556:in `new'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-core-5.21.29/lib/inspec/cli.rb:556:in `<top (required)>'
        from <internal:C:/inspec/inspec/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/inspec/inspec/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/inspec/inspec/embedded/lib/ruby/gems/3.1.0/gems/inspec-bin-5.21.29/bin/inspec:10:in `<top (required)>'
        from C:/inspec/inspec/bin/inspec:261:in `load'
        from C:/inspec/inspec/bin/inspec:261:in `<main>'
```
There is a ffi.gemspec at that location. It contains the following:
```
require File.expand_path("../lib/#{File.basename(__FILE__, '.gemspec')}/version", __FILE__)

Gem::Specification.new do |s|
  s.name = 'ffi'
  s.version = FFI::VERSION
  s.author = 'Wayne Meissner'
  s.email = 'wmeissner@gmail.com'
  s.homepage = 'https://github.com/ffi/ffi/wiki'
  s.summary = 'Ruby FFI'
  s.description = 'Ruby FFI library'
  if s.respond_to?(:metadata)
    s.metadata['bug_tracker_uri'] = 'https://github.com/ffi/ffi/issues'
    s.metadata['changelog_uri'] = 'https://github.com/ffi/ffi/blob/master/CHANGELOG.md'
    s.metadata['documentation_uri'] = 'https://github.com/ffi/ffi/wiki'
    s.metadata['wiki_uri'] = 'https://github.com/ffi/ffi/wiki'
    s.metadata['source_code_uri'] = 'https://github.com/ffi/ffi/'
    s.metadata['mailing_list_uri'] = 'http://groups.google.com/group/ruby-ffi'
  end
  s.files = `git ls-files -z`.split("\x0").reject do |f|
    f =~ /^(\.|bench|gen|libtest|nbproject|spec)/
  end

  # Add libffi git files
  lfs = `git --git-dir ext/ffi_c/libffi/.git ls-files -z`.split("\x0")
  # Add autoconf generated files of libffi
  lfs += %w[ configure config.guess config.sub install-sh ltmain.sh missing fficonfig.h.in ]
  # Add automake generated files of libffi
  lfs += `git --git-dir ext/ffi_c/libffi/.git ls-files -z *.am */*.am`.gsub(".am\0", ".in\0").split("\x0")
  s.files += lfs.map do |f|
    File.join("ext/ffi_c/libffi", f)
  end

  s.extensions << 'ext/ffi_c/extconf.rb'
  s.rdoc_options = %w[--exclude=ext/ffi_c/.*\.o$ --exclude=ffi_c\.(bundle|so)$]
  s.license = 'BSD-3-Clause'
  s.require_paths << 'ext/ffi_c'
  s.required_ruby_version = '>= 2.3'
  s.add_development_dependency 'rake', '~> 13.0'
  s.add_development_dependency 'rake-compiler', '~> 1.0'
  s.add_development_dependency 'rake-compiler-dock', '~> 1.0'
  s.add_development_dependency 'rspec', '~> 2.14.1'
end
```

**Comment by pbarrette** [comment]
I uninstalled InSpec entirely and installed version 4.52.9 which works correctly.

It appears that the train-vmware plugins don't work correctly with InSpec 5.21.29

**Comment by rlakey** [comment]
For reference https://github.com/inspec/inspec/issues/6411

**Comment by rlakey** [comment]
I've updated our train-vmware package to remove the `train` depedency and it seems to be working with the latest versions of InSpec. Please try it out.

https://github.com/vmware/dod-compliance-and-automation/commit/5c3a4327b4281d9af2c90649e08f4707203dec03
