### ISSUE TITLE
INSPEC: VCSA-70-000077, 148, 158, 292 erroring on HTTP

### ISSUE THREAD

**Issue by pbarrette** [vmware/dod-compliance-and-automation#130]
### Describe the bug

All checks using the HTTP transport produce errors:
```
error
HTTP GET on https://vcentername/api/appliance/system/global-fips status 
undefined method `<<' for nil:NilClass
--------------------------------
error
Control Source Code Error C:/inspec/Profiles/vmware-vsphere-7.0-stig-baseline/vcenter/controls/VCSA-70-000077.rb:1 
undefined method `<<' for nil:NilClass
```

### Reproduction steps

1. Execute an inspec scan against the named controls.

### Expected behavior

The scan should either successfully scan the HTTP API endpoint or just be marked as manual checks.

### Additional context

It appears that InSpec forces the HTTP call to be executed remotely unless you are using the local transport.
See here: [https://github.com/inspec/inspec/blob/main/lib/inspec/resources/http.rb#L33](https://github.com/inspec/inspec/blob/main/lib/inspec/resources/http.rb#L33)

It seems that since the scans are using the `-t vmware://` transport, the call fails.
Executing the individual controls without the `-t vmware://` succeeds, but that breaks other controls.

The full results message is as follows:
```
                "results":
                    [
                        {
                        "backtrace":
                            [
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:305:in `block in load_powershell_command'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:304:in `each'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:304:in `load_powershell_command'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:252:in `http_command'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:207:in `run_http'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:188:in `status'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/resources/http.rb:52:in `status'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:134:in `block (3 levels) in its'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `each'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `inject'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `block (2 levels) in its'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block (2 levels) in let'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (3 levels) in fetch_or_store'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `fetch'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:157:in `block (2 levels) in fetch_or_store'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-support-3.10.3/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:156:in `block in fetch_or_store'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:155:in `fetch_or_store'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/memoized_helpers.rb:317:in `block in let'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:159:in `should'",
                            "C:/inspec/Profiles/vmware-vsphere-7.0-stig-baseline/vcenter/controls/VCSA-70-000077.rb:63:in `block (3 levels) in load_with_context'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner_rspec.rb:82:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:166:in `run_tests'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:137:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:304:in `exec'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/base_cli.rb:35:in `start'",
                            "C:/inspec/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.52.9/bin/inspec:11:in `<top (required)>'",
                            "C:/inspec/inspec/bin/inspec:301:in `load'",
                            "C:/inspec/inspec/bin/inspec:301:in `<main>'"
                            ],
                        "code_desc": "HTTP GET on https://vcentername/api/appliance/system/global-fips status ",
                        "exception": "NoMethodError",
                        "message": "undefined method `<<' for nil:NilClass",
                        "resource_class": "http",
                        "resource_params": "[\"https://vcentername/api/appliance/system/global-fips\", {:method=>\"GET\", :headers=>{\"vmware-api-session-id\"=>\"XXXXXXXXXXXXXXXXXXXXXX\"}, :ssl_verify=>false}]",
                        "run_time": 0.0009751,
                        "start_time": "2023-02-02T09:42:17-06:00",
                        "status": "failed"
```

**Comment by rlakey** [comment]
The VMware transport is basically the same as the local transport and all it really does setup the connection to vCenter via Connect-VIServer and Connecto-SSOAdminServer if using our updated transport.

If you are not using our provided transport then these http calls will not work because i removed the platform detection from it so that it could utilize other resources like http so that we could run all these controls at once and not have to do separate profiles or run the same profile twice with separate transports.

**Comment by rlakey** [comment]
I wouldn't rule out something with inspec as well since that version is really old you went back to.  I remember some point years ago the http resource did not work on windows.

**Comment by pbarrette** [comment]
I know it's an old version, but it's the one recommended [here](https://github.com/vmware/dod-compliance-and-automation/tree/master/vsphere/7.0/vsphere/inspec/vmware-vsphere-7.0-stig-baseline).

I had initially installed 5.21.29, but as noted [here](https://github.com/vmware/dod-compliance-and-automation/issues/128#issuecomment-1412312449), the train-vmware plugin breaks inspec completely.

Also, if I run the following command, the HTTP transport works and the control is marked as compliant:
inspec exec . --input-file .\inputs-example.yml --show-progress --reporter=cli json:C:\Inspec\Reports\vcsa.json --controls=VCSA-70-000077

**Comment by pbarrette** [comment]
I've been looking at this a bit more. Couldn't all of these be changed to PowerCLI requests?

VCSA-70-000077
Invoke-GetSystemGlobalFips

VCSA-70-000148
Invoke-GetLoggingForwarding

VCSA-70-000158
Invoke-GetTimesync

VCSA-70-000292
Invoke-GetRecovery

**Comment by rlakey** [comment]
Had to refresh my memory...these http checks only work when ran from Linux.  Windows is not returning the correct output.

I confirmed there's an issue with InSpec 5.21.29 and the custom train-vmware. When trying to install from that version we get an unrelated error that I'm still tracking down.

For the other cmdlets proposed I did not know they existed at the time but yes absolutely we can move to those except for Invoke-GetRecovery.  That one is not returning the status of backups being scheduled or not.

**Comment by pbarrette** [comment]
```
(Invoke-ListRecoveryBackupSchedules).default


recurrence_info : @{hour=23; days=System.Object[]; minute=59}
enable          : True
parts           : {seat, common}
location        : proto://redacted/path
location_user   : redacted
retention_info  : @{max_count=10}
```
