### ISSUE TITLE
[vSphere][7.0][ESXI-70-000078] Inspec throws profile error when checking SSL

### ISSUE THREAD

**Issue by pstearns** [vmware/dod-compliance-and-automation#158]
### Describe the bug

ESXI-70-000078 - The ESXi host must use DOD-approved certificates.
Fails with: 
```
PROFILE_ERROR -- Test: ssl_certificate for 'hostname' issuer_organization 
Message: ["libraries/ssl_certificate.rb:93:in `issuer'", "libraries/ssl_certificate.rb:147:in `issuer_attribute'", "libraries/ssl_certificate.rb:110:in `issuer_organization'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:134:in `block (3 levels) in its'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `each'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `inject'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:133:in `block (2 levels) in its'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block (2 levels) in let'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (3 levels) in fetch_or_store'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `fetch'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (2 levels) in fetch_or_store'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-support-3.11.1/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:178:in `block in fetch_or_store'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch_or_store'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block in let'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-its-1.3.0/lib/rspec/its.rb:159:in `should'", "/opt/stigtools/dod-compliance-and-automation/vsphere/7.0/vsphere/inspec/vmware-vsphere-7.0-stig-baseline/esxi/controls/ESXI-70-000078.rb:83:in `block (4 levels) in load_with_context'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `instance_exec'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `block in run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.18.14/lib/inspec/runner_rspec.rb:97:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.18.14/lib/inspec/runner.rb:183:in `run_tests'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.18.14/lib/inspec/runner.rb:154:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.18.14/lib/inspec/cli.rb:366:in `exec'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-5.18.14/lib/inspec/base_cli.rb:35:in `start'", "/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-5.18.14/bin/inspec:11:in `<top (required)>'", "/opt/inspec/embedded/bin/inspec:25:in `load'", "/opt/inspec/embedded/bin/inspec:25:in `<main>'"]
```
Running the individual check:
```
  ×  ESXI-70-000078: The ESXi host must use DOD-approved certificates.
     ×  ssl_certificate for 'hostname' issuer_organization
     undefined method `issuer' for #<String:0x0000000005d40378>
```

### Reproduction steps

Run: `inspec exec ./vmware-vsphere-7.0-stig-baseline/esxi -t vmware:// --input vmhostName=hostname  --controls ESXI-70-000078`
Error:  ssl_certificate for 'hostname' issuer_organization
                 undefined method `issuer' for #<String:0x0000000005d40378

### Expected behavior

Properly read the hosts SSL certificate.

### Additional context

Oddly the vCenter check VCSA-70-000195, which utilizes the  same ssl_certificate library succeeds.

**Comment by rlakey** [comment]
Can the system you are running the scan from access the ESXi host on 443 and resolve "hostname"?

**Comment by pstearns** [comment]
You are correct. The ESXi firewall was blocking the scan IP for 443. Simple thing I overlooked. Thank you.

**Comment by pstearns** [comment]
Resolved. ssl_certificate could not reach host on 443.
