### ISSUE TITLE
PR 76 broke vmware-vcsa-6.7-stig-baseline inspec profile

### ISSUE THREAD

**Issue by potatoqualitee** [vmware/dod-compliance-and-automation#78]
### Describe the bug

https://github.com/vmware/dod-compliance-and-automation/pull/76 introduces syntax errors that I can't get past.

```
inspec exec C:\github\dod-compliance-and-automation\vsphere\6.7\vcsa\inspec\vmware-vcsa-6.7-stig-baseline -t ssh://root@vcenter.ad.local -i $home\.ssh\vspherekey --show-progress --reporter=cli json:C:\Inspec\Reports\vcsa.json
Traceback (most recent call last):
        22: from C:/opscode/inspec/embedded/bin/inspec:32:in `<main>'
        21: from C:/opscode/inspec/embedded/bin/inspec:32:in `load'
        20: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.52.9/bin/inspec:11:in `<top (required)>'
        19: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/base_cli.rb:35:in `start'
        18: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        17: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        16: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        15: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        14: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/cli.rb:304:in `exec'
        13: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:136:in `run'
        12: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:102:in `load'
        11: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:102:in `each'
        10: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/runner.rb:120:in `block in load'
         9: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile.rb:218:in `collect_tests'
         8: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/dependencies/dependency_set.rb:63:in `each'
         7: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/dependencies/dependency_set.rb:63:in `each'
         6: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/dependencies/dependency_set.rb:64:in `block in each'
         5: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile.rb:223:in `collect_tests'
         4: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile.rb:223:in `each'
         3: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile.rb:228:in `block in collect_tests'
         2: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile_context.rb:154:in `load_control_file'
         1: from C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile_context.rb:170:in `load_with_context'
C:/opscode/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.52.9/lib/inspec/profile_context.rb:170:in `instance_eval': C:/github/dod-compliance-and-automation/vsphere/6.7/vcsa/inspec/vmware-vcsa-6.7-stig-baseline/vami/controls/VCLD-67-000003.rb:15: syntax error, unexpected local variable or method, expecting end-of-input (SyntaxError)
  desc  'rationale', ''
```

When I deleted VCLD-67-000003.rb just to test, it broke at like 5, then 6 so I reverted back to commit bcc15bcea128543632e34cd0f29301e1c9c211d3 and it worked as expected.

### Reproduction steps
Download the latest version of this repo and attempt to run it however works in your env. This was tested on Windows.

```bash
inspec exec C:\github\dod-compliance-and-automation\vsphere\6.7\vcsa\inspec\vmware-vcsa-6.7-stig-baseline -t ssh://root@vcenter.ad.local -i $home\.ssh\vspherekey --show-progress --reporter=cli json:C:\Inspec\Reports\vcsa.json
```

### Expected behavior

Should work as expected as it does in bcc15bcea128543632e34cd0f29301e1c9c211d3 from PR #75 (75 may have broken something else, but this worked at least)

```
inspec exec C:\github\dod-compliance-and-automation\vsphere\6.7\vcsa\inspec\vmware-vcsa-6.7-stig-baseline -t ssh://root@vcenter.ad.local -i $home\.ssh\vspherekey --show-progress --reporter=cli json:C:\Inspec\Reports\vcsa.json
F..............................................................................................................................................................................................................................FF..........FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF.FF........F...FFFF..F..FFFF.F..F....F.........................................F........................................F..F.F..............................FFFF.........................F.FFF..F...................F..................F.FF....F.............................................................................................................F..F...................................................................................................................................................................................................................F...............FF.FF...F.......FF.....FF..F.......................................................................................................................................................................................F.FFFFF......FF.................FF...........F..F.....F............FF********..***.FFF.*F*FFFFFFFFF****....F...............................................................................................................................................................................................................................................................................................................................................................F..........................................................................................................FF..F.....

Profile: InSpec Overlay Profile for the VMware vCenter Service Appliance 6.7 DISA STIG (vmware-vcsa-6.7-stig-baseline)
Version: 6.7.0 Version 1 Release 1
Target:  ssh://root@vcenter.ad.local:22

etc etc

 [PASS]  V-239713: vSphere UI must restrict its cookie path.
     [PASS]  XML /usr/lib/vmware-vsphere-ui/server/conf/context.xml ["/Context/@sessionCookiePath"] is expected to cmp == "/ui"


Profile Summary: 259 successful controls, 55 control failures, 16 controls skipped
Test Summary: 1595 successful, 268 failures, 17 skipped
```

### Additional context

Once this is fixed, I'll explore setting up a GitHub Action that tests parsing.

**Comment by rlakey** [comment]
Give it another try now. I pushed some fixes for the missing quotes that broke a few controls.

https://github.com/vmware/dod-compliance-and-automation/commit/5a60d4450c106f41bb4c08085f965060f5d0aa89

**Comment by potatoqualitee** [comment]
Looks great! I was able to run everything I needed. Thanks for this project and the prompt response.
